// Backward-compatible re-export — all imports from "./tauri" resolve to electron.ts
export { isDesktop } from './electron';
export const isTauri = true;
export type {
  CreateTaskInput,
  ExecutionRecord,
  JupyterStatus,
  SaveResult,
  ScheduledTask,
  ToolStatus,
  UpdateTaskInput,
} from './electron';
export {
  addFilesToWorkspace,
  addTextToWorkspace,
  appIdentifier,
  appVersion,
  channelName,
  checkForUpdates,
  checkSidecarVersion,
  detectTools,
  exportLogs,
  knowledgeCategories,
  knowledgeDelete,
  knowledgeGet,
  knowledgeList,
  knowledgeSave,
  knowledgeSaveCategories,
  logDebug,
  newDatedWorkspace,
  openExternal,
  openWorkspaceBase,
  pickFolder,
  profileExplainConfig,
  profileInteraction,
  profileManifest,
  profileValidatePatch,
  profileWritePatch,
  projectConfigRead,
  projectConfigSummary,
  restartRuntime,
  runtimePassword,
  sandboxStatus,
  saveTextFile,
  schedulerClearHistory,
  schedulerCreate,
  schedulerDelete,
  schedulerDeleteExecution,
  schedulerFireNow,
  schedulerHistory,
  schedulerList,
  schedulerToggle,
  schedulerUpdate,
  setWorkspace,
  setWorkspaceBase,
  skillsAddSource,
  skillsApplyScheme,
  skillsConfig,
  skillsDeleteScheme,
  skillsList,
  skillsPickSource,
  skillsReadScheme,
  skillsRemoveSource,
  skillsSaveScheme,
  skillsSchemes,
  skillsSetEnabled,
  startRuntime,
  windowBehavior,
  workspaceBase,
  workspacePath,
} from './electron';
