// Backward-compatible re-export — all imports from "./tauri" resolve to electron.ts
export { isDesktop } from './electron';
export const isTauri = true;
export type {
  CreateTaskInput,
  ExecutionRecord,
  JupyterStatus,
  SaveResult,
  ScheduledTask,
  ToolStatus,
  UpdateTaskInput,
} from './electron';
export {
  addFilesToWorkspace,
  addTextToWorkspace,
  appIdentifier,
  appVersion,
  channelName,
  checkForUpdates,
  detectTools,
  exportLogs,
  logDebug,
  newDatedWorkspace,
  openExternal,
  openWorkspaceBase,
  pickFolder,
  profileInteraction,
  profileManifest,
  profileValidatePatch,
  profileWritePatch,
  restartRuntime,
  runtimePassword,
  saveTextFile,
  schedulerClearHistory,
  schedulerCreate,
  schedulerDelete,
  schedulerDeleteExecution,
  schedulerFireNow,
  schedulerHistory,
  schedulerList,
  schedulerToggle,
  schedulerUpdate,
  setWorkspace,
  setWorkspaceBase,
  startRuntime,
  workspaceBase,
  workspacePath,
} from './electron';
