// Backward-compatible re-export — all imports from "./tauri" resolve to electron.ts
export { isDesktop } from "./electron";
export const isTauri = true;
export {
  startRuntime,
  restartRuntime,
  runtimePassword,
  addFilesToWorkspace,
  addTextToWorkspace,
  openExternal,
  saveTextFile,
  workspacePath,
  workspaceBase,
  setWorkspaceBase,
  openWorkspaceBase,
  setWorkspace,
  newDatedWorkspace,
  pickFolder,
  detectTools,
  logDebug,
  checkForUpdates,
  exportLogs,
  channelName,
  appIdentifier,
  appVersion,
  schedulerList,
  schedulerCreate,
  schedulerUpdate,
  schedulerDelete,
  schedulerToggle,
  schedulerFireNow,
  schedulerHistory,
  schedulerDeleteExecution,
  schedulerClearHistory,
} from "./electron";
export type {
  JupyterStatus,
  SaveResult,
  ToolStatus,
  ScheduledTask,
  CreateTaskInput,
  UpdateTaskInput,
  ExecutionRecord,
} from "./electron";